[discord]
token = ""  # Your Discord bot token here
guild_id = ""  # Your Discord server ID here

[printer]
endpoint = "http://localhost:8080"  # Your printer endpoint here
api_key = ""  # Your printer API key here
